name: ServerMCInutile
version: 1.0.0
main: com.pacchetto.core.ServerMCPlugin
api-version: '1.20'
author: Huawetto
commands:
  fun:
    description: Comando principale plugin FUN
    usage: /fun <guide|cheat>
permissions:
  servermc.fun:
    default: true
